### ISSUE TITLE
my fault, please guide us how to used it clearly

### ISSUE THREAD

**Issue by sandikodev** [ohjeongwook/DumpFlash#29]
just trying fetch/pull with latest commit
i dont really know how to used this, even just for showsup my nand flash information 🙃

**Comment by sandikodev** [comment]
but with this old git commited
`git checkout 4bd490d6acc338d20ba902c5aa77de587a26103d`


i can dump nand flash information with clearly
`python2 DumpFlash.py -i`
![Screenshot from 2020-10-27 04-26-09](https://user-images.githubusercontent.com/33443311/97230566-bcbb5580-180c-11eb-963c-14cdb49c7baf.png)

**Comment by drdoinstuff** [comment]
Not sure what your asking but please see your previous post; I think it's related.

**Comment by mh4nx7net** [comment]
thanks, 
then, how can i read the flash memory with latest of this new command line option commited `51cf034b0bf63746bd84bb0efd4cd17172ff6039` ?

because in the previous commit line , like `20db2d3`
i can download mynand flash.bin just with 
`python dumpflash.py -r mynand.bin`
so sorry about this trivial question
